### ISSUE TITLE
Requirement of a Continuous Integration Tool

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/2017.fossasia.org#13]
[2017.fossasia.org](https://2017.fossasia.org) needs a `Continuous Integration` tool to take care that there is no "breaking of the build" while changing any part of the code, this would reduce the overhead of manual testing.

According to this article [Open Source - 6 top continuous integration tools](https://opensource.com/business/15/7/six-continuous-integration-tools) there are majorly 6 top CI tools in Open Source:
- [Jenkins](https://jenkins.io/index.html)
- [Buildbot](http://buildbot.net/)
- [Travis CI](https://travis-ci.org/)
- [Strider](https://github.com/Strider-CD/strider)
- [GoCD](https://www.go.cd/)
- [Integrity](http://integrity.github.io/)

**Comment by joerx** [comment]
To answer the question first: Since it's hosted on Github, use Travis. Free, hosted, well integrated.

But what you are asking for is an empty box. A CI tool does nothing by itself - it just runs a series of steps you are telling it to run. Build instructions, test cases, etc. So we need to decide what exactly we want it to do first. 

What you are suggesting is a QA tool - I'm not sure that would make a lot of sense for a mostly static website. How exactly does your current (manual) test process look like? What are you looking for when testing? What are common errors you are encountering?

**Comment by sudheesh001** [comment]
I think this is an overkill for a statically hosted website and good to close.

**Comment by mariobehling** [comment]
No need.
